name: mfexport_ci
channels:
- conda-forge
dependencies:
- python
- ipython
- jupyter
- notebook
- ipykernel
- matplotlib
- pyyaml
- numpy
- pandas
- xarray
- gdal
- fiona
- rasterio
- shapely
- pyproj
- codecov
- coverage
- flake8
- pytest
- sphinx
- numpydoc
- nbsphinx
- sphinx-copybutton
- sphinx_rtd_theme
- pip
- pip:
    - git+https://github.com/modflowpy/flopy@develop
    - git+https://github.com/aleaf/gis-utils@develop
